### ISSUE TITLE
Formally write the non-functional requirements of the project

### ISSUE THREAD

**Issue by Charles-Spencer-Blancas** [Charles-Spencer-Blancas/ECSE428-Project#2]

**Comment by AayushBhat** [comment]
1. The web application shall have a user-friendly interface with a response time of less than 3 seconds for all actions.
2. The application shall allow users to search for items using tags and filters with a minimum of 3 search options and a maximum response time of 5 seconds.
3. The platform shall allow students to create and manage their own profiles with a maximum completion time of 3 minutes.
4. The platform shall allow for private communication between buyers and sellers with a maximum response time of 2 seconds.
5. The application shall track the history of items bought and sold by users for at least 1 year.
6. The application shall be responsive and accessible on various devices desktop devices with a resolution of at least 720p and responsive design for all screen sizes.

**Comment by Charles-Spencer-Blancas** [comment]
#30 for part of 1 and part of 2

#28 for 3 and 4
